---
- name: Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  tags:
    - always

- name: Ensure custom Terminal profile is added.
  shell: "open {{ dotfiles_path }}/{{ item }}.terminal"
  with_items: "{{ terminal_themes }}"
  changed_when: false
  when: "terminal_themes[0] != terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  shell: "defaults write com.apple.terminal 'Default Window Settings' -string {{ terminal_themes[0] }}"
  changed_when: false
  when: "terminal_themes[0] != terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  shell: "defaults write com.apple.terminal 'Startup Window Settings' -string {{ terminal_themes[0] }}"
  changed_when: false
  when: "terminal_themes[0] != terminal_theme.stdout"

- name: "OS X Preferences"
  command: "defaults write {{ item.domain }} {{ item.key }} {{ item.value }}"
  with_items: "{{ osx.prefs }}"
  become: true
  become_user: "{{ install_user }}"

- name: "Killing affected apps"
  command: "killall {{ item }}"
  with_items:
    - "Dock"
    - "Finder"
    - "SystemUIServer"
